services:
  # catalogapi:
  #   image: ${DOCKER_REGISTRY-}catalogapi
  #   build:
  #     context: .
  #     dockerfile: Services/Catalog/CatalogAPI/Dockerfile

  catalogdb:
    image: postgres:17.4

volumes:
    postgres_catalog:


